version: '3.8'

services:
  # GuardFlow AI Services
  ai-services:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardflow-ai-services
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - DATABASE_URL=postgresql://guardflow:guardflow123@postgres:5432/guardflow_ai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - ./models:/models
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: guardflow-ai-postgres
    environment:
      - POSTGRES_DB=guardflow_ai
      - POSTGRES_USER=guardflow
      - POSTGRES_PASSWORD=guardflow123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guardflow -d guardflow_ai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: guardflow-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: guardflow-ai-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: guardflow-ai-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    depends_on:
      - prometheus

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: guardflow-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - ai-services
    restart: unless-stopped

  # Model Training Service
  model-trainer:
    build:
      context: .
      dockerfile: Dockerfile.trainer
    container_name: guardflow-ai-trainer
    environment:
      - DATABASE_URL=postgresql://guardflow:guardflow123@postgres:5432/guardflow_ai
      - REDIS_URL=redis://redis:6379
      - MODEL_PATH=/models
    volumes:
      - ./models:/models
      - ./training_data:/training_data
    depends_on:
      - postgres
      - redis
    restart: "no"
    profiles:
      - training

  # Data Processing Service
  data-processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    container_name: guardflow-ai-processor
    environment:
      - DATABASE_URL=postgresql://guardflow:guardflow123@postgres:5432/guardflow_ai
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  default:
    name: guardflow-ai-network
